### ISSUE TITLE
 Problem building 'buffer without document' with Aphrodite

### ISSUE THREAD

**Issue by alvim54** [biw/gatsby-plugin-aphrodite#1] opened 2018-11-19 14:06 UTC
Moving from [#7996](https://github.com/gatsbyjs/gatsby/issues/7996) on gatsby repo:

I'm using Gatsby v2 and aphrodite on my site.
I've updated to 2.0.5 and now got the following error on `gatsby build`:

```
success Building production JavaScript and CSS bundles — 16.017 s

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  811 |         // place without a document), so guard against that.
  812 |         if (typeof document === "undefined") {
> 813 |             throw new Error("Cannot automatically buffer without a document");
      | ^
  814 |         }
  815 | 
  816 |         // If we're not already buffering, schedule a call to flush the


  WebpackError: Cannot automatically buffer without a document
  
  - chunk-9cf6448a.js:813 injectGeneratedCSSOnce
    [lib]/[aphrodite]/es/chunk-9cf6448a.js:813:1
  
  - chunk-9cf6448a.js:839 injectStyleOnce
    [lib]/[aphrodite]/es/chunk-9cf6448a.js:839:1
  
  - chunk-9cf6448a.js:943 injectAndGetClassName
    [lib]/[aphrodite]/es/chunk-9cf6448a.js:943:1
  
  - chunk-9cf6448a.js:1154 css
    [lib]/[aphrodite]/es/chunk-9cf6448a.js:1154:1
  
  - resolveLTR.js:34 resolveLTR
    [lib]/[react-with-styles-interface-aphrodite]/lib/utils/resolveLTR.js:34:1
  
  - aphroditeInterfaceFactory.js:71 Object.resolveLTR
    [lib]/[react-with-styles-interface-aphrodite]/lib/aphroditeInterfaceFactory.js:71:1
  
  - ThemedStyleSheet.js:60 resolveLTR
    [lib]/[react-with-styles]/lib/ThemedStyleSheet.js:60:1
  
  - Cell.js:106 Cell
    [lib]/[cinnecta-ui]/lib/components/Cell.js:106:1
  
  
  - bootstrap:19 ua
    lib/webpack/bootstrap:19:1
  
  - bootstrap:24 a.render
    lib/webpack/bootstrap:24:1
  
  
  
  - gatsby-ssr.js:32 
    [lib]/[gatsby-plugin-aphrodite]/gatsby-ssr.js:32:1
  
  - chunk-ff1dea3c.js:1027 Object.renderStatic
    [lib]/[aphrodite]/lib/chunk-ff1dea3c.js:1027:1
  
  - gatsby-ssr.js:31 renderAphrodite
    [lib]/[gatsby-plugin-aphrodite]/gatsby-ssr.js:31:1

```

Any clue?

**Comment by biw** [comment] 2018-11-20 19:58
@alvim54 I'm having trouble replicating the issue, could you try `rm -rf node_modules` then reinstalling? 

If that doesn't work, could you post some of the code in your `src` folder that uses `aphrodite` so I can try to recreate the issue?

**Comment by mweisert** [comment] 2019-02-26 19:17
I'm having the same problem as @alvim54 .  Sorry, I'm newer to using Gatsby.  I'm using the 'gatsby-starter-forty' template which bundled aphrodite.  Let me know if there is a specific file I can share - thanks in advance!

**Comment by biw** [comment] 2019-02-27 01:31
Hi @mweisert, thanks for reaching out 😄

Would you mind sharing you `package.json` & `gatsby-config.js` files?

**Comment by mweisert** [comment] 2019-02-27 13:57
Thanks for getting back to me.  Here are the files - let me know if you need anything else

[Archive.zip](https://github.com/biw/gatsby-plugin-aphrodite/files/2910577/Archive.zip)

**Comment by biw** [comment] 2019-02-27 23:33
@mweisert, it looks like you missing `gatsby-plugin-aphrodite` in your `gatsby-config.js` file.

You'll need to add that to the `plugins` section 😄

Let me know if that works!

**Comment by mweisert** [comment] 2019-03-03 22:14
That did - thanks so much!  Out of curiosity, did something change where it didn't require that before?  I opened a backup version that had built successfully in the past and it didn't have that line.

**Comment by biw** [comment] 2019-03-04 07:14
@mweisert, glad it worked! 😄 It didn't, that's odd!

I'm going to close this as solved, if anyone hits this again, please feel free to comment

**Comment by jpalmieri** [comment] 2019-05-21 22:21
This seems to have reappeared for me when upgrading to aphrodite 2.3.0. Any idea @biw?

**Comment by biw** [comment] 2019-05-21 23:35
@jpalmieri I will look into it this week 😄

**Comment by szmarci** [comment] 2019-06-10 16:12
I have the same problem :(

**Comment by idanci** [comment] 2020-01-03 20:43
@biw hey, did you have a change to look into it?

**Comment by biw** [comment] 2020-01-08 21:45
I am unable to reproduce this with node `12.14.1`, gatsby `2.18.18`, aphrodite `2.4.0`, and gatsby-plugin-aphrodite `2.0.5`

**Comment by joshuanewman1993** [comment] 2020-04-23 10:09
I have the same problem. Is there a known fix out for this?

**Comment by ethantmanns** [comment] 2020-05-13 00:13
Hey everyone! Wanted to come in and share what I found the issue to be in case it helps anyone else. Excuse my raggedy terminology since I'm newer to frontend lol. My issue was I was trying to reference styles outside of my functional component. So I had some elements written out as class variables, and moving those into being declared inside my react function fixed the issue. I don't really know how Aphrodite or Gatsby work in depth, but I imagine it needs to exist within the component because that's where the styles are being generated and applied 🤷 

Hope this can help someone!

**Closed** 2020-08-24 20:38 UTC
