### ISSUE TITLE
Build issue when using plugin with Gatsby V3

### ISSUE THREAD

**Issue by TMUND** [biw/gatsby-plugin-aphrodite#10] opened 2021-04-29 18:03 UTC
Hello `gatsby-plugin-aphrodite` 👋 

Recently I've been trying to update our app from using Gatsby v2 to Gatsby v3 and one of the issues I run into during `gatsby build` is this one: 

<img width="1240" alt="Screen Shot 2021-04-29 at 11 03 13 AM" src="https://user-images.githubusercontent.com/10443437/116597492-84d7bc80-a8da-11eb-8226-d030dd2eaa7e.png">

I'm wondering if this plugin is not supporting Gatsby v3 yet (_if so, are there plans to?_) or whether I'm doing something wrong.

**Comment by biw** [comment] 2021-04-29 18:26
Hey @TMUND, thanks for reaching out! I haven't looked into supporting Gatsby 3 yet, but just found [this](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers). I might be able to do something in the next week or so, but if you want to give it a go I'd be happy to accept a PR 😄

**Comment by TMUND** [comment] 2021-04-29 18:40
Hey @biw, thanks for the quick response. 

I can certainly attempt an update based on the link you provided. If I get stuck or something looks out of place I'll post an update here.

**Comment by biw** [comment] 2021-04-29 18:42
A good starting point might be to try to see if `gatsby-plugin-aphrodite` works on a fresh gatsby 3.0 install. I'm not sure if you seeing the issue above due to the plugin or something else (since it's throwing on `images`, which isn't used in the plugin codebase.

**Comment by biw** [comment] 2021-04-29 21:37
Sure! Any help is awesome! A good test for the PR might be to see if a Gatsby V3 + the updated `gatsby-plugin-aphrodite` can support rendering one `<div style={style.div} />` tag. Let me know how it goes 😄

**Comment by TMUND** [comment] 2021-05-02 23:38
Hey @biw, based on your comment:

>I'm not sure if you seeing the issue above due to the plugin or something else (since it's throwing on images, which isn't used in the plugin codebase.

I dug a little deeper and you are right, my issue was with `gatsby-plugin-image` but the errors blamed `gatsby-plugin-aphrodite`. Thanks for the catch 🙌

<br>

I tried opening up a PR for Gatsby V3 support which implements the change described here [HERE](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#for-plugin-maintainers) ...which is just this change in the `package.json` file. 

```
    "gatsby": "^2.32.0 || ^3.0.0"
```

...however, I'm getting access rights warning when trying to push. FWIW I'm not seeing any warnings/issues with `gatsby-plugin-aphrodite` when running `yarn` locally on a fresh Gatsby V3 install, with or without the change above.

**Comment by biw** [comment] 2021-05-03 21:45
Sweet, I made the change and things are live in [v2.1.1](https://github.com/biw/gatsby-plugin-aphrodite/releases/tag/v2.1.1). I also added some tests to automate builds in #11 and will fix the PR later this week. Thanks for your help! I'm going to close this since it seems the issue is fixed 😄

**Closed by biw** 2021-05-03 21:45 UTC
